name: test
run-name: ${{github.actor}} is running tests.
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4
    steps:
      - run: |
          echo "Setting up dependencies ..."
          cd scripts
          source setup_dependencies $(nproc) || exit 1
      - run: |
          echo "Building library ..."
          cd scripts
          source build.sh $(nproc) || exit 2
      - run: |
          echo "Running tests ..."
          cd build
          ctest -V

      
